const { contextBridge, ipcRenderer } = require("electron")

contextBridge.exposeInMainWorld("engram", {
  getWorkspaceConfig:  ()         => ipcRenderer.invoke("workspace:get"),
  saveWorkspaceConfig: (config)   => ipcRenderer.invoke("workspace:save", config),
  setupWorkspace:      (config)   => ipcRenderer.invoke("workspace:setup", config),
  triggerReindex:      (path)     => ipcRenderer.invoke("index:trigger", path),
  getIndexStatus:      ()         => ipcRenderer.invoke("index:status"),
  query:               (text)     => ipcRenderer.invoke("query:send", text),
  getTags:             (area)     => ipcRenderer.invoke("tags:get", area),
  getTag:              (tagId)    => ipcRenderer.invoke("tags:getOne", tagId),
  createTag:           (data)     => ipcRenderer.invoke("tags:create", data),
  getDocs:             (tagId)    => ipcRenderer.invoke("docs:get", tagId),
  addDoc:              (data)     => ipcRenderer.invoke("docs:add", data),
  createDocument:      (data)     => ipcRenderer.invoke("docs:create", data),
  editDocument:        (data)     => ipcRenderer.invoke("docs:edit", data),
  getIssues:           (tagId)    => ipcRenderer.invoke("issues:get", tagId),
  updateIssue:         (issue)    => ipcRenderer.invoke("issues:update", issue),
  runIssues:           (tagId)    => ipcRenderer.invoke("issues:run", tagId),
  getHistory:          (tagId)    => ipcRenderer.invoke("git:history", tagId),
  revertCommit:        (hash)     => ipcRenderer.invoke("git:revert", hash),
  getWiring:           (tagId)    => ipcRenderer.invoke("wiring:get", tagId),
  saveWiring:          (data)     => ipcRenderer.invoke("wiring:save", data),
  getJBMap:            (jbRef)    => ipcRenderer.invoke("wiring:jb", jbRef),
  traceFromDCS:        (c, ch)    => ipcRenderer.invoke("wiring:trace", { card: c, channel: ch }),
  openFolder:          ()         => ipcRenderer.invoke("dialog:openFolder"),
  openFiles:           ()         => ipcRenderer.invoke("dialog:openFiles"),
  getConfig:           (key)      => ipcRenderer.invoke("workspace:getkey", key),
  stageChange:         (tagId, field, oldVal, newVal) => ipcRenderer.invoke("stage:change", { tagId, field, oldVal, newVal }),
  classifyIssue:       (issueId, classification, comment) => ipcRenderer.invoke("issues:update", { id: issueId, classification, comment }),
  addDocuments:        () => ipcRenderer.invoke("docs:addFromDialog"),
  reindex:             () => ipcRenderer.invoke("index:reindexAll"),
})
